### ISSUE TITLE
Cannot find the jar file

### ISSUE THREAD

**Issue by asifm** [NetLogo/K-Means-Extension#2]
I'm new to netlogo. I was trying to get this extension installed by placing the folder in the default extensions directory. I think the folder is supposed to have a jar file, but I can't locate one.

**Comment by nicolaspayette** [comment]
Hi @asifm! As far as I can tell, the release file for the extension does have the right jar. Maybe you downloaded the source code instead? In any case, try this link:

https://github.com/NetLogo/K-Means-Extension/releases/download/1.0.0/k-means.zip.

I'm closing this issue for now, but feel free to write back if you have more trouble.

**Comment by asifm** [comment]
Thanks. Indeed. In my hurry, I had downloaded the source zip. Sorry about the false report.
